- custom_components/abbfreeathome-ci/config_flow.py
- custom_components/abbfreeathome-ci/manifest.json
This PR adds zeroconf discovery to the ABB free@home integration.
> Adds zeroconf support to the integration

- custom_components/abbfreeathome-ci/config_flow.py
- custom_components/abbfreeathome-ci/const.py
- custom_components/abbfreeathome-ci/manifest.json
- custom_components/abbfreeathome-ci/strings.json
- custom_components/abbfreeathome-ci/translations/en.json
This further refines the config flow experience. Primarily the description and title text, and how it's populated.
> Refine the config flow and text

- custom_components/abbfreeathome_ci/manifest.json
- custom_components/abbfreeathome_ci/switch.py
Addresses #9 , upgrades the PyPi package to latest and uses the SwitchActuator term vs Switch.
> Use the term SwitchActuator vs Switch

- custom_components/abbfreeathome_ci/__init__.py
Filter down the list of devices to just what we want integrated into Home Assistant.
> Add a filter to the list of devices to integrate

- custom_components/abbfreeathome_ci/binary_sensor.py
- custom_components/abbfreeathome_ci/event.py
- custom_components/abbfreeathome_ci/sensor.py
- custom_components/abbfreeathome_ci/strings.json
- custom_components/abbfreeathome_ci/switch.py
- custom_components/abbfreeathome_ci/translations/en.json
This PR adds the Window/Door sensor to the integration.
> Add window/door sensor to integration

- custom_components/abbfreeathome_ci/__init__.py
- custom_components/abbfreeathome_ci/light.py
This adds a new light entity with the DimmingActuator device from the PyPi package.
There's no way for me to test this, so feedback is required before implementing this.
> Add new light entity

- custom_components/abbfreeathome_ci/binary_sensor.py
- custom_components/abbfreeathome_ci/strings.json
- custom_components/abbfreeathome_ci/translations/en.json
This adds new binary sensors, smoke detector and carbon monoxide. Fyi @derjoerg
> Add smoke detector, carbon monoxide sensor

- custom_components/abbfreeathome_ci/manifest.json
- custom_components/abbfreeathome_ci/sensor.py
- custom_components/abbfreeathome_ci/strings.json
- custom_components/abbfreeathome_ci/translations/en.json
This adds the window position sensor recently added to the PyPi package.
> Adds new window position sensor

- custom_components/abbfreeathome_ci/manifest.json
Also bump PyPi package version.
> Bump Version 0.11.0

- custom_components/abbfreeathome_ci/binary_sensor.py
- custom_components/abbfreeathome_ci/button.py
- custom_components/abbfreeathome_ci/event.py
- custom_components/abbfreeathome_ci/light.py
- custom_components/abbfreeathome_ci/manifest.json
- custom_components/abbfreeathome_ci/sensor.py
- custom_components/abbfreeathome_ci/switch.py
> Use get_devices_by_class vs get_device_by_class

- custom_components/abbfreeathome_ci/binary_sensor.py
- custom_components/abbfreeathome_ci/event.py
- custom_components/abbfreeathome_ci/manifest.json
- custom_components/abbfreeathome_ci/strings.json
- custom_components/abbfreeathome_ci/translations/en.json
> Implement ForceOnOffSensor

- custom_components/abbfreeathome_ci/__init__.py
- custom_components/abbfreeathome_ci/manifest.json
- custom_components/abbfreeathome_ci/valve.py
> Implement HeatingActuator

- custom_components/abbfreeathome_ci/__init__.py
- custom_components/abbfreeathome_ci/climate.py
> Implement RoomTemperatureController

- custom_components/abbfreeathome_ci/__init__.py
- custom_components/abbfreeathome_ci/lock.py
> Implement lock-entity

- custom_components/abbfreeathome_ci/strings.json
- custom_components/abbfreeathome_ci/translations/en.json
> Update strings.json with common keys

- custom_components/abbfreeathome_ci/translations/de.json
> Add german translation

- README.md
- custom_components/abbfreeathome_ci/manifest.json
> Bump Version 0.14.0

- custom_components/abbfreeathome_ci/__init__.py
- custom_components/abbfreeathome_ci/manifest.json
This is currently not working as expected
closes #110
> Remove virtual device support

- custom_components/abbfreeathome_ci/manifest.json
Bumping to initial release 1.0.0. Also bumping the python package dependency to the latest.
> Bump Version 1.0.0

- custom_components/abbfreeathome_ci/manifest.json
> Bump library version to 1.18.0

- custom_components/abbfreeathome_ci/diagnostics.py
- custom_components/abbfreeathome_ci/manifest.json
Bump external PyPi dependency.
> Bump Version 1.2.0

- custom_components/abbfreeathome_ci/binary_sensor.py
- custom_components/abbfreeathome_ci/climate.py
- custom_components/abbfreeathome_ci/cover.py
- custom_components/abbfreeathome_ci/event.py
- custom_components/abbfreeathome_ci/light.py
- custom_components/abbfreeathome_ci/lock.py
- custom_components/abbfreeathome_ci/manifest.json
- custom_components/abbfreeathome_ci/select.py
- custom_components/abbfreeathome_ci/sensor.py
- custom_components/abbfreeathome_ci/switch.py
- custom_components/abbfreeathome_ci/valve.py
This pull-requests covers the needed rework of the modified callback handling done in #kingsleyadam/local-abbfreeathome/pull/165
> Rework callback handling of library

- custom_components/abbfreeathome_ci/manifest.json
- custom_components/abbfreeathome_ci/number.py
> Set correct UoM for Batter Power

- custom_components/abbfreeathome_ci/climate.py
- custom_components/abbfreeathome_ci/manifest.json
> Make HVAC-Action detection independent from connected valve

- custom_components/abbfreeathome_ci/manifest.json
This will add support for the temperature controller requested by @Staccato77
> Bump library to 2.1.1; Add support for Busch Jaeger 62842 U-WL

- custom_components/abbfreeathome_ci/climate.py
- custom_components/abbfreeathome_ci/light.py
- custom_components/abbfreeathome_ci/manifest.json
> Rework climate

- README.md
Adds a small note about hardware compatibility.
> Add note about earlier version of the hardware compatibility.

- README.md
- custom_components/abbfreeathome_ci/manifest.json
- custom_components/abbfreeathome_ci/strings.json
- custom_components/abbfreeathome_ci/switch.py
- custom_components/abbfreeathome_ci/translations/de.json
- custom_components/abbfreeathome_ci/translations/en.json
The title says it all.
The idea came out of the following discussion: https://github.com/kingsleyadam/local-abbfreeathome-hass/discussions/152
> Add possibility to control LED of switch- and dimming-sensors

- custom_components/abbfreeathome_ci/manifest.json
- custom_components/abbfreeathome_ci/switch.py
> Correctly use `getattr` in `turn_on` and `turn_off`

- .devcontainer/devcontainer.json
- .pre-commit-config.yaml
- README.md
- dev-requirements.txt
This adds a dev container configuration to the repository to ensure we're all working in the same environment when adding changes to the repo.
- Adding pre-commit check to ensure ruff linting and formatting is caught before creating a pull-request.
- Installing a virtual environment with Home Assistant, and integration dependencies (local-abbfreeathome) are installed.
- Default formatters to ensure we're all formatting the documents the same.
> Add dev container support

- custom_components/abbfreeathome_ci/manifest.json
Adds in new function mapping added in https://github.com/kingsleyadam/local-abbfreeathome/pull/201
> Bump local-abbfreeathome to 2.5.4, adds additional function for DesDoorRingingSensor

- .github/workflows/release.yml
- .github/workflows/ruff.yaml
- README.md
- custom_components/abbfreeathome_ci/__init__.py
- custom_components/abbfreeathome_ci/binary_sensor.py
- custom_components/abbfreeathome_ci/button.py
- custom_components/abbfreeathome_ci/climate.py
- custom_components/abbfreeathome_ci/config_flow.py
- custom_components/abbfreeathome_ci/const.py
- custom_components/abbfreeathome_ci/cover.py
- custom_components/abbfreeathome_ci/diagnostics.py
- custom_components/abbfreeathome_ci/event.py
- custom_components/abbfreeathome_ci/light.py
- custom_components/abbfreeathome_ci/lock.py
- custom_components/abbfreeathome_ci/manifest.json
- custom_components/abbfreeathome_ci/number.py
- custom_components/abbfreeathome_ci/select.py
- custom_components/abbfreeathome_ci/sensor.py
- custom_components/abbfreeathome_ci/strings.json
- custom_components/abbfreeathome_ci/switch.py
- custom_components/abbfreeathome_ci/translations/de.json
- custom_components/abbfreeathome_ci/translations/en.json
- custom_components/abbfreeathome_ci/valve.py
Promote 1.7.0 to main from beta branch
> Release 1.7.0

- custom_components/abbfreeathome_ci/manifest.json
Cutting beta 1 release for 1.8.0
> Bump Beta Version 1.8.0b1

- README.md
- custom_components/abbfreeathome_ci/manifest.json
This bumps the integration to release 1.9.0, make some small updates to the readme around SSL cert location.
> Bump Release 1.9.0, README update
