kingsleyadam/local-abbfreeathome-hass

custom_components/abbfreeathome-ci/__init__.py
custom_components/abbfreeathome-ci/config_flow.py
custom_components/abbfreeathome-ci/manifest.json
custom_components/abbfreeathome-ci/strings.json
custom_components/abbfreeathome-ci/translations/en.json

This PR makes a number of enhancements to the setup flow.
- The zeroconf and user setup won't follow the exact same flow. Making the code easier to manage.
- Use the SysAP serial number to set the unique id on both zeroconf and user flows. This should ensure that zerconf doesn't recognize the device as a new device even if the SysAP name is changed. This also ensures the user can't setup the integration twice for the same SysAP.
- When deleting the integration, ensure the websocket gets closed.

Make a number of adjustments to the integration setup

---

custom_components/abbfreeathome-ci/config_flow.py
custom_components/abbfreeathome-ci/manifest.json

The description placeholder were not getting set everywhere. Adjust this to set it more globally.

Set description placeholders more globally

---

README.md
custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/switch.py

This exposes additional attributes to the device, including
- manufacturer
- model
- serial number
- suggested area
The suggested area will come from the user configuration in the ABB interface.
I've also made some adjustments to the README.

Expose device info, close websocket properly

---

custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/switch.py

This addresses #8 
This adds the SysAP as a new device and links all switches to it. You'll see this as a new device in the list of devices for the integration.
Right now it won't have any controls, the ABB local api doesn't provide much functionality for controlling the SysAP (that I can tell). But if we find anything we can add it.
It will list information about the SysAP including:
- Firmware Version
- Hardware Version
- Serial Number
It will also allow you to "Visit" the SysAP configuration page with a link to the configuration URL.

Add SysAP as a new device, link switches to it

---

custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/const.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/services.yaml
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

This adds a new "action" to Home Assistant that'll allow a user to view the list of devices in their setup.
Bump version to patch since this is added to help debug an issue.

Adds new device dump service

---

custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/manifest.json

This adds the `WIRELESS_RF` interface for missing wireless devices.
Remove unnecessary if statement from previous patch version.
Bump version

Add WIRELESS_RF as allowed interface

---

custom_components/abbfreeathome_ci/manifest.json

Bumps PyPi package to 1.3.2 to include https://github.com/kingsleyadam/local-abbfreeathome/pull/30

Bump PyPi package to 1.3.2

---

README.md
custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/const.py
custom_components/abbfreeathome_ci/diagnostics.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/services.yaml
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

This address #21 , instead of using a service call to get the device info, this tags up the diagnostic download for the implementation.
When downloading the diagnostics for the integration it'll include the entire Free@Home configuration in addition to information about the integration (manifest) and HA instance.
I've redacted the longitude and latitude to protect the users location, as well as the sysAP Name and `uartSerialNumber`. Some people (myself included) may use indetifiable information in the SysAP name.
I've also removed the dump service completely.

Implement diagnostics settings for integration

---

custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/binary_sensor.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/sensor.py
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/switch.py
custom_components/abbfreeathome_ci/translations/en.json

This addresses #24 , This adds support for both sensor and binary sensor platforms in Home Assistant.
The initial implementation supports
- Motion Detector - Both Motion (Binary Sensor) and Illuminance (Sensor)
- Switch Sensor (Binary Sensor)
A note and something that may be confusing, the switch sensor only follows the state of the switch on physical button presses. It doesn't follow the state of the light it may be controlling. If you turn off a light with Home Assistant, the Switch Sensor won't be updated to reflect the light state. Because of this we should probably also implement an Event when the Switch is physically pressed, the event will trigger regardless of if the state is already On/Off.
This also includes a translations update to ensure we can translate the name of the …

Adds support for sensor and binary sensor platforms

---

README.md
custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/binary_sensor.py
custom_components/abbfreeathome_ci/event.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

This adds a new Event entity type to be associated with a device and can be used in automations. Reasoning behind this type and when/why to use it is also included in the README file.

Add new Event entity for sensor switch's

---

custom_components/abbfreeathome_ci/binary_sensor.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/sensor.py

This addresses #27 , only add a sensor if there's a value. Some devices may not have all the same sensors, so we should only add a new sensor if it has a value other than None.
New version of the PyPi package ensures all sensors have an initial value of None to avoid any attribute exceptions.

Only add a new sensor if it has a value other than None

---

custom_components/abbfreeathome_ci/binary_sensor.py
custom_components/abbfreeathome_ci/event.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/sensor.py
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

This PR makes a number of adjustments for future additions, and a smaller one for now.
- Ensure the `channel_name` is set for all sensors in the entity description. If this is set and no translation key is set, it'll use this as the device name. If the translation key is set it'll use the translation key for the device name.
- This required a bit of rework to set the `name` property of the entity description as `name` has no setter.
- Add `channel_id` as a translation placeholder value.
- Use `channel_id` in the translation of the SwitchSensor binary sensor and event entities.

Adjust naming of sensors.

---

custom_components/abbfreeathome_ci/config_flow.py
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

Add in support for integration reconfiguration.
This will use new methods only available in 2024.11.0, so this won't work initially once released. But we're targeting this integration as a core HA integration and want to keep up-to-date on it's current methods.

Add reconfigure integration flow.

---

custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/config_flow.py
custom_components/abbfreeathome_ci/const.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

This grants the ability to exclude orphan channels from the Free@Home configuration.
The default in new integration setup will be false (exclude orphan channels). But because I don't want to change existing behavior, when this migrates the configs to a newer version it'll keep the current value of True.
Right now, to change this you must first delete the integration and re-add.
In the next release of Home Assistant this integration will be able to be "reconfigured" and this value can be changed.

Add options to include/exclude orphan nodes

---

README.md
custom_components/abbfreeathome_ci/diagnostics.py
custom_components/abbfreeathome_ci/manifest.json

This addresses https://github.com/kingsleyadam/local-abbfreeathome-hass/issues/47
I'm adding in the pairing name and function name to the diagnostics download. I'm ensure the order of items int he dict is alphabetical so the function name is easily read with function id, etc.
I'm also updating the README to adjust text around device support with the list of supported functions by platform.
Example Output
```json
"ABB7F4FEB38E": {
"deviceReboots": "23",
"floor": "03",
"room": "07",
"interface": "TP",
"deviceId": "9100",
"displayName": "2nd Floor > 3rd Floor Landing Rocker",
"unresponsive": false,
"unresponsiveCounter": 0,
"defect": false,
"channels": {
"ch0000": {
"displayName": "2nd Floor > 3rd Floor Landing Rocker",
"floor": "03",
"function": "FID_SWITCH_SENSOR",
"functionID": "0", …
```

Add function, pairing to diagnostics, update readme.

---

custom_components/abbfreeathome_ci/event.py
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

This adds the `DesDoorRingingSensor` to the event sensor. I'm implementing a lambda function as a callback to know the event type by Free@Home class.
I'm not sure how this will scale if we have any complicated state (more than just boolean). But this works pretty well for the current setup. It can always be adjusted later.
For @derjoerg to test.

Add DesDoorRingingSensor to event sensor

---

custom_components/abbfreeathome_ci/diagnostics.py

This adds the parameter-names to the diagnostics output.
@kingsleyadam : I need your help! The parameters on the device-level are correctly filled, but not on the channel level 😢 I don't understand the source of the problem

Add parameter-names to Diagnostics

---

README.md
custom_components/abbfreeathome_ci/binary_sensor.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/sensor.py
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

This implements all entities of a Weatherstation into HA. There is only one drawback:
The thresholds for all the alarm sensors (brightness, temperature, wind) are available in the parameters of each device-class and - at least from my perspective - it would be nice to implement them as additional attributes in HA.
But - for now - F@H doesn't send an update over the websocket when a parameter is changed through the F@H-WebGUI. So the parameters would stay in HA unchanged until the integration is reloaded (e.g. through a HA restart). That's the reason I haven't included them.
Perhaps it might be something to think about - I don't know if this is possible - to implement an automatic daily "re-discover"/"re-fetch" in the integration?

Implement all entities of a Weatherstation

---

custom_components/abbfreeathome_ci/config_flow.py
custom_components/abbfreeathome_ci/manifest.json

Closes #65 
This will catch ClientConnectionError, throw an error to the user and logs the exception.

Catch ClientConnectionError on config flow

---

README.md
custom_components/abbfreeathome_ci/config_flow.py
custom_components/abbfreeathome_ci/const.py
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

This PR will check for System Access Point 2.6.0 before proceeding with setup.
For the ZeroConf discovery, this will abandon setup and the user won't be prompted to setup a new device. For the user setup flow the user will be prompted with an error that their version is too old with the actual version they are running.
I've also added a Prerequisites section to the README to inform users of the requirements for using this integration.
closes #63

Check for SysAP version 2.6.0 or newer

---

custom_components/abbfreeathome_ci/config_flow.py
custom_components/abbfreeathome_ci/manifest.json

If there are no errors a key error would get thrown trying to lookup the "base" errors. Use dict `get` function which will return a `None` type value.

Fix key error on user setup flow

---

README.md
custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/binary_sensor.py
custom_components/abbfreeathome_ci/button.py
custom_components/abbfreeathome_ci/config_flow.py
custom_components/abbfreeathome_ci/const.py
custom_components/abbfreeathome_ci/diagnostics.py
custom_components/abbfreeathome_ci/event.py
custom_components/abbfreeathome_ci/light.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/sensor.py
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/switch.py
custom_components/abbfreeathome_ci/translations/en.json
hacs.json

This is purely a documentation update.
- Updates any reference to the free@home brand to `Busch/ABB-free@home` to match-up with ABB branding. They seem to have two different namings, probably depending on region?
- Internally I've just referenced ABB-free@home. The title of the integration and name in hacs as `Busch/ABB-free@home`.
- https://www.busch-jaeger.nl/producten/systemen/busch-freehome
- https://new.abb.com/low-voltage/products/building-automation/product-range/abb-freeathome

Use term ABB-free@home

---

README.md
custom_components/abbfreeathome_ci/binary_sensor.py
custom_components/abbfreeathome_ci/event.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

This makes a number of adjustments to events and binary sensors.
- Removes the `SwitchSensor` and `ForceOnOffSensor` from the binary_sensor as these do not make sense as sensors. They're moment in time "events" and will be treated just as events.
- Add the following new events
- `BlindSensor`
- `DimmingSensor`
- Also, adjust the sensors for `SwitchSensor`, `ForceOnOffSensor` to use the new state options.

Add new events/adjust, remove binary sensors

---

custom_components/abbfreeathome_ci/binary_sensor.py
custom_components/abbfreeathome_ci/button.py
custom_components/abbfreeathome_ci/climate.py
custom_components/abbfreeathome_ci/event.py
custom_components/abbfreeathome_ci/light.py
custom_components/abbfreeathome_ci/lock.py
custom_components/abbfreeathome_ci/sensor.py
custom_components/abbfreeathome_ci/switch.py
custom_components/abbfreeathome_ci/valve.py

The attribute `has_entity_name` must be true for all new integrations. See: https://developers.home-assistant.io/docs/core/entity#has_entity_name-true-mandatory-for-new-integrations
This PR ensure's all platforms have this set to True (it's false by default). And that it's set in the entity description and not at the class level.
For binary sensor instead of removing `translation_key` from the entity_description in the entity constructor, I'm overriding the parent entity `translation_key` property. This is how it should properly be done

Ensure has_entity_name is true everywhere

---

custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/select.py
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/en.json

Closes #78 
This adds the new platform `select` with the forced positions for SwitchActuator, CoverActuator, and DimmingActuator.
Some work on the python package side will still need to be required before this can be merged in, marking this as a draft for now.
I've kept an option to set `available` property up to the Python package, fyi @derjoerg, if the python package implements `available` then it'll be inherited by Home Assistant entities.

Add new select platform for forced options

---

custom_components/abbfreeathome_ci/button.py
custom_components/abbfreeathome_ci/climate.py
custom_components/abbfreeathome_ci/light.py
custom_components/abbfreeathome_ci/lock.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/switch.py
custom_components/abbfreeathome_ci/valve.py

Setting the has_entity_name has some adverse affects with how free@home device > channel relationships are.
Even though it's required by Home Assistant, it does say
> The entity's name property only identifies the data point represented by the entity, and should not include the name of the device or the type of the entity. So for a sensor that represents the power usage of its device, this would be “Power usage”.
This means that setting the entity name to the free@home channel_name is also not the correct use. And you end up with long entity names and id's that'll most certainly have to be adjusted by the user.
But leaving the entity name out would then use the device name, which may or may not be helpful based on how the user has setup free@home, and in those cases where a device have …

Revert has_entity_name=True

---

custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/cover.py

Nothing major, but Home Assistant linter was complaining about a few spots in the cover.py code. Most important is the return type for `supported_features` being an int when it should be `CoverEntityFeature`.

Fix cover linting from Home Assistant

---

custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/config_flow.py
custom_components/abbfreeathome_ci/manifest.json

Closes #97 
This PR will grab the Home Assistant ClientSession object using the `async_get_clientsession` helper method and pass it along to the `FreeAtHomeApi` and `FreeAtHomeSettings` classes.
This is being applied both in the `__init__` used on every load of the integration. And in the `config_flow` when setting up the integration for the first time.

Use the Home Assistant Client Session Object

---

README.md
custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/config_flow.py

This adds the ability to setup and configure the integration via the `configuration.yaml` file.
Although it's not my preferred approach, especially since errors in configuration can get lost in the logs, some people do prefer it and it's required according to the [integration quality scale](https://developers.home-assistant.io/docs/integration_quality_scale_index/#no-score).
Closes #99

Add ability to setup via configuration.yaml

---

custom_components/abbfreeathome_ci/manifest.json

With this added, when debug logging is enabled on the integration it'll include debug logs from both the integration and the PyPi package.

Add PyPi packages to loggers manifest

---

README.md
custom_components/abbfreeathome_ci/config_flow.py
custom_components/abbfreeathome_ci/manifest.json

This moves the check on whether the SysAP has api support to the Python package which added a check in https://github.com/kingsleyadam/local-abbfreeathome/pull/131.
Also adds support for two additional functions added in https://github.com/kingsleyadam/local-abbfreeathome/pull/130

Use the FreeAtHomeSettings class to check SysAP compatibility.

---

custom_components/abbfreeathome_ci/light.py
custom_components/abbfreeathome_ci/manifest.json

Closes #124 
The ABB SysAP doesn't seem to work with floats very well, so we need to convert the dimmer brightness to an integer before setting it.
I don't have any way to test this, this has only come up on a newly added dimmer actuator type.

Convert dimmer brightness to int before setting

---

custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/manifest.json

This depends on the relevant PR of the library

Bugfix: Add interface `smokealarm` after firmware upgrade to 3.5.0

---

README.md
custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/binary_sensor.py
custom_components/abbfreeathome_ci/button.py
custom_components/abbfreeathome_ci/climate.py
custom_components/abbfreeathome_ci/config_flow.py
custom_components/abbfreeathome_ci/const.py
custom_components/abbfreeathome_ci/cover.py
custom_components/abbfreeathome_ci/event.py
custom_components/abbfreeathome_ci/light.py
custom_components/abbfreeathome_ci/lock.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/number.py
custom_components/abbfreeathome_ci/select.py
custom_components/abbfreeathome_ci/sensor.py
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/switch.py
custom_components/abbfreeathome_ci/translations/de.json
custom_components/abbfreeathome_ci/translations/en.json
custom_components/abbfreeathome_ci/valve.py

Closes #157 
This implements the possibilities to have sub-devices for each "multi-device" in F@H, which can be placed independently on the floorplan.
This can increase the device-count drastically. In my case it increased from 86 to 181 devices.
The default is false (also for existing installation), so the change needs to be specific wanted by the user.
Additionally, what I saw during my tests: If you switch on this feature, the existing multi-device will preserve the original set area (this needs to be manually removed), only with a fresh installation the physical (multi) device will not have an area assigned.
I also encountered (once again) a small bug from ABB:
E.g. a virtual switch and a virtual energy meter are correctly displayed in HA as one device, but a virtual binary sensor …

Implement possibility to have sub-devices

---

custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/switch.py
custom_components/abbfreeathome_ci/translations/de.json
custom_components/abbfreeathome_ci/translations/en.json

This implements support Welcome IP Mute Actuator/Sensor.
I don't fully understand the behavior of the sensor, but as it was requested ...
The switch correctly activates or deactivates the Mute-function of the Panel. The changes are also reflected with the F@H app.
But if the mute-function on the panel is used, then the switch stays as it is, but the event is fired.

Implement Welcome IP Mute Actuator/Sensor

---

custom_components/abbfreeathome_ci/binary_sensor.py
custom_components/abbfreeathome_ci/sensor.py
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/switch.py
custom_components/abbfreeathome_ci/translations/de.json
custom_components/abbfreeathome_ci/translations/en.json

This PR is based on the [PR #216](https://github.com/kingsleyadam/local-abbfreeathome/pull/216) of local-abbfreeathome and adds support for the new BlockableMotionDetector. Both a binary sensor for the motion detection and a switch for blocking the motion detection have been added.
Please note that at least version 3.1.0 of local-abbfreeathome is needed. I did not update the manifest.json because I wasn't sure if I am allowed to change it.

Support for BlockableMotionDetector

---

README.md
custom_components/abbfreeathome_ci/__init__.py
custom_components/abbfreeathome_ci/config_flow.py
custom_components/abbfreeathome_ci/const.py
custom_components/abbfreeathome_ci/manifest.json
custom_components/abbfreeathome_ci/strings.json
custom_components/abbfreeathome_ci/translations/de.json
custom_components/abbfreeathome_ci/translations/en.json

This PR adds the ability to connect to the free@home SysAP via SSL for a secure connection. The SysAP provides the certificate to be used for verification.
SSL can also be setup without verification for those who would rather not provide the SSL certificated, but this isn't recommended and will log a warning on each load.
This will add new fields in the integration configuration to setup SSL. When adding an integration for the first time you'll only be prompted for these new fields if you provide an `https` schema. This ensure's the SSL options don't clutter up the interface if `https` is not requested.

Add SSL Support
